<?php
ini_set('display_errors', 1); 
ini_set('display_startup_errors', 1); 
error_reporting(E_ALL);
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

include_once('../wp-config.php' );
global $wpdb;

require('../wp-load.php');


if (isset($_POST) && !empty($_POST)) {
//echo "<pre>";print_r($_POST);exit;
if (isset($_POST['studentName']) && !empty($_POST['studentName'])) {
    /*$getpostdetails= get_post($_POST['jobid']);
    $get_post_metadata= get_post_meta($_POST['jobid']);
    $country = $get_post_metadata['country'][0];
    $job_location_extension = strtolower($country);
    if(isset($get_post_metadata['country']) && !empty($get_post_metadata['country'])){
        $job_location = $get_post_metadata['job_location_'.$job_location_extension][0];
    }else{
        $job_location='';
    }*/

require '../wp-content/themes/bento-child/vendor/PHPMailer/PHPMailer/src/Exception.php';
require '../wp-content/themes/bento-child/vendor/PHPMailer/PHPMailer/src/PHPMailer.php';
require '../wp-content/themes/bento-child/vendor/PHPMailer/PHPMailer/src/SMTP.php';

//Load Composer's autoloader
require '../wp-content/themes/bento-child/vendor/autoload.php';

/* FIle Upload*/
if (!function_exists('wp_handle_upload')) {
           require_once(ABSPATH . 'wp-admin/includes/file.php');
       }
      //$uploadedfile = $_FILES['file'];
      //$upload_overrides = array('test_form' => false);
      //$movefile = wp_handle_upload($uploadedfile, $upload_overrides);
      //if ($movefile && !isset($movefile['error'])) {
         //echo "File Upload Successfully";
   //} else {
        /**
         * Error generated by _wp_handle_upload()
         * @see _wp_handle_upload() in wp-admin/includes/file.php
         */
        //echo $movefile['error'];
   // }
     /* FIle Upload End*/  
     
		$studentName = stripslashes($_POST['studentName']);
		$courseTitle = stripslashes($_POST['courseTitle']);
		$courseSponser = stripslashes($_POST['courseSponser']);
		//$month = $_POST['month'];
		$date = $_POST['date'];
		//$year = $_POST['year'];
		$examinationLocation = $_POST['examinationLocation'];
		$relationship = $_POST['relationship'];
		$examMonitorEmployee = $_POST['examMonitorEmployee'];
		$employerAddress = $_POST['employerAddress'];
		$city = $_POST['city'];
		$state = $_POST['state'];
		$zipCode = $_POST['zipCode'];
		$jobTitle = $_POST['jobTitle'];
		$businessPhone = $_POST['businessPhone'];
		$studentDecName = $_POST['studentDecName'];
		$wwocertificationNumber = $_POST['wwocertificationNumber'];
        $createdDate = date('Y-m-d H:i:s');
        $modifiedDate = '';
		
		/*$get_job_location_email = $wpdb->get_results("SELECT email FROM wp_job_location_email WHERE (job_location = '". $country ."')");
		
		if(isset($get_job_location_email) && !empty($get_job_location_email)){
			$job_location_wise_email = $get_job_location_email[0]->email;
		}else{
			$job_location_wise_email = get_option( 'admin_email' );
		}*/

		$insert = $wpdb->insert('wp_wwo_decl_self_paced_train_exm_frms', array(
			'studentName' => "$studentName",
			'courseTitle' => "$courseTitle",
			'courseSponser' => "$courseSponser",
			'date' => "$date",
			'examinationLocation' => "$examinationLocation",
			'relationship' => "$relationship",
			'examMonitorEmployee' => "$examMonitorEmployee",
			'employerAddress' => "$employerAddress",
			'city' => $city,
			'state' => $state,
			'zipCode' => $zipCode,
			'jobTitle' => $jobTitle,
			'businessPhone' => $businessPhone,
			'studentDecName' => "$studentDecName",
			'wwocertificationNumber' => "$wwocertificationNumber",
			'createdDate' => "$createdDate",
			'modifiedDate' => "$modifiedDate"
			));
		if (false === $insert) {
				echo $wpdb->last_error;
		} else {
            echo "Sucess";
		}
	} else {
		echo "xasdsadFailed";
		exit( var_dump( $wpdb->last_query ) );
		//header('Location: ' . site_url() . '/incubator');
	}
}
